apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gitminsoo/GCP_GKE.git
    targetRevision: main
    path: manifests/gke-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gke-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
